### ISSUE TITLE
[Prototype] Level 2 (Dungeon Level)

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/GameJam-FallDown#11]
PREREQUISITE

- The issue #1 and #2 must be complete at least.
- OPTIONAL: You can wait for issue #10 to be finished. That would require to communicate to whoever is working on level one to avoid conflicts on Github commits.

**Comment by GHGFaber** [comment]
Handling Level 2 💯

**Comment by stephaniechoi725** [comment]
ill help out with level 2
