### ISSUE TITLE
[Prototype] Platform Functionality

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/GameJam-FallDown#2]
The platform functionality that has...:
- A platform where it goes from level 1 to level 2. In addition, on level 2, if the player reach the end, go to main menu for now.
- Simple collision blocks for world building
- Block that breaks if you step on it.
- Hazard collisions like spikes. Other implementations of this idea is great and we would love to see it!

**Comment by GHGFaber** [comment]
Handling platform 👍🏼
